import mongoose from 'mongoose';
import dotenv from 'dotenv';
import { ProductCategory } from '../models/ProductCategory.js';
import { Product } from '../models/Product.js';
import { Service } from '../models/Service.js';
import { Industry } from '../models/Industry.js';

dotenv.config();

export const categoriesData = [
  {
    name: 'Industrial Adhesives',
    slug: 'adhesives',
    description: 'PVAC white glue, D2, D3, PVC, Acrylic, and PUR adhesives engineered for woodworking and panel processing.',
    displayOrder: 1,
  },
  {
    name: 'Woodworking Tools',
    slug: 'woodworking-tools',
    description: 'Precision tooling including CNC bits, multiboring bits, saw blades, and tailored customised tools.',
    displayOrder: 2,
  },
  {
    name: 'Woodworking Machinery',
    slug: 'machinery',
    description: 'Industrial panel saws, multi-boring units, edge banders, CNC routers, and cold/hot presses.',
    displayOrder: 3,
  },
  {
    name: 'Machine Spares',
    slug: 'machine-spares',
    description: 'Original mechanical, electrical, and computerized replacement spare parts for panel processing machinery.',
    displayOrder: 4,
  },
  {
    name: 'PVC Edge Banding & Hardware',
    slug: 'edge-banding-hardware',
    description: 'High-grade PVC edge banding tapes, architectural furniture hinges, channels, and assembly fittings.',
    displayOrder: 5,
  },
];

export const productsData = [
  // Adhesives - LOCKPRO Range
  {
    name: 'Lockpro VUS PUR Adhesives',
    slug: 'lockpro-vus-pur-adhesives',
    brand: 'LOCKPRO',
    categoryName: 'Industrial Adhesives',
    categorySlug: 'adhesives',
    shortDescription: 'Industrial reactive polyurethane (PUR) adhesive engineered for panel processing and edge banding.',
    fullDescription: 'Lockpro VUS PUR Adhesives are formulated for high-performance bonding in modular furniture and industrial woodworking. Engineered for extreme moisture and heat resistance during continuous production lines.',
    image: '/assets/products/lockpro-1k-pur.png',
    mockupImage: '/assets/products/lockpro-1k-pur.png',
    applications: ['Modular Furniture', 'Modular Kitchens', 'Panel Processing', 'Woodworking Industries'],
    isFeatured: true,
    isAvailable: true,
  },
  {
    name: 'Lockpro WR 3 (D3)',
    slug: 'lockpro-wr-3-d3',
    brand: 'LOCKPRO',
    categoryName: 'Industrial Adhesives',
    categorySlug: 'adhesives',
    shortDescription: 'Water-resistant D3 grade white adhesive for modular furniture, kitchens, and door manufacturing.',
    fullDescription: 'Lockpro WR 3 (D3) is an advanced water-resistant emulsion adhesive specially developed for woodworking environments where moisture protection and dependable bonding are vital.',
    image: '/assets/products/lockpro-wr3-bucket.png',
    mockupImage: '/assets/products/lockpro-wr3-mockup.png',
    applications: ['Modular Kitchens', 'Door Manufacturing', 'Modular Furniture', 'Woodworking Industries'],
    isFeatured: true,
    isAvailable: true,
  },
  {
    name: 'Lockpro 808',
    slug: 'lockpro-808',
    brand: 'LOCKPRO',
    categoryName: 'Industrial Adhesives',
    categorySlug: 'adhesives',
    shortDescription: 'Heavy-duty industrial adhesive formulation for demanding woodworking and surface lamination.',
    fullDescription: 'Lockpro 808 is designed for rapid tack, high bond integrity, and consistent application across wood, composite panels, and laminate bonding lines.',
    image: '/assets/products/lockpro-808.png',
    mockupImage: '/assets/products/lockpro-808.png',
    applications: ['Modular Furniture', 'Door Manufacturing', 'Woodworking Industries'],
    isFeatured: true,
    isAvailable: true,
  },
  {
    name: 'Lockpro 808 PR',
    slug: 'lockpro-808-pr',
    brand: 'LOCKPRO',
    categoryName: 'Industrial Adhesives',
    categorySlug: 'adhesives',
    shortDescription: 'High-performance adhesive primer and bonding agent for panel manufacturing lines.',
    fullDescription: 'Lockpro 808 PR offers enhanced bond strength and chemical stability for heavy industrial processing, modular shutter fabrication, and multi-substrate applications.',
    image: '/assets/products/lockpro-808-pr.png',
    mockupImage: '/assets/products/lockpro-808-pr.png',
    applications: ['Modular Furniture', 'Panel Processing', 'Woodworking Industries'],
    isFeatured: true,
    isAvailable: true,
  },
  {
    name: 'LockPro 707',
    slug: 'lockpro-707',
    brand: 'LOCKPRO',
    categoryName: 'Industrial Adhesives',
    categorySlug: 'adhesives',
    shortDescription: 'Specialty woodworking adhesive for assembly bonding, edge banding, and joinery.',
    fullDescription: 'LockPro 707 provides reliable joint retention, clean handling, and balanced open time for assembly shops, modular cabinetmakers, and timber joinery.',
    image: '/assets/products/lockpro-707.png',
    mockupImage: '/assets/products/lockpro-707.png',
    applications: ['Modular Furniture', 'Modular Kitchens', 'Woodworking Industries'],
    isFeatured: true,
    isAvailable: true,
  },

  // Adhesives - ADHHESI PRO Brand
  {
    name: 'PVAC White Glue',
    slug: 'pvac-white-glue',
    brand: 'ADHHESI PRO',
    categoryName: 'Industrial Adhesives',
    categorySlug: 'adhesives',
    shortDescription: 'Core polyvinyl acetate white glue manufactured for industrial woodworking, furniture, and door manufacturing.',
    fullDescription: 'MODUPRO INNOVATION manufactures and trades high-quality PVAC White Glue under the Adhhesi Pro brand. First established in the adhesive business in 2015, this formulation delivers reliable bonding for modular units, doors, and timber structures.',
    image: '/assets/products/lockpro-wr3-bucket.png',
    mockupImage: '/assets/products/lockpro-wr3-mockup.png',
    applications: ['Modular Furniture', 'Modular Kitchens', 'Door Manufacturing', 'Woodworking Industries'],
    isFeatured: true,
    isAvailable: true,
  },
  {
    name: 'Certified D3 Adhesives',
    slug: 'certified-d3-adhesives',
    brand: 'ADHHESI PRO',
    categoryName: 'Industrial Adhesives',
    categorySlug: 'adhesives',
    shortDescription: 'Water-resistant certified D3 adhesive formulation for demanding exterior-facing interior joinery.',
    fullDescription: 'Certified D3 grade adhesive engineered to resist high ambient humidity and water contact, ideal for modular kitchens, bathroom vanities, and door lamination.',
    image: '/assets/products/lockpro-wr3-bucket.png',
    mockupImage: '/assets/products/lockpro-wr3-mockup.png',
    applications: ['Modular Kitchens', 'Door Manufacturing', 'Woodworking Industries'],
    isFeatured: false,
    isAvailable: true,
  },
  {
    name: 'Commercial D3 Adhesives',
    slug: 'commercial-d3-adhesives',
    brand: 'ADHHESI PRO',
    categoryName: 'Industrial Adhesives',
    categorySlug: 'adhesives',
    shortDescription: 'Cost-effective commercial D3 adhesive balancing moisture resistance and production efficiency.',
    fullDescription: 'Formulated for standard industrial production runs requiring D3 moisture protection with dependable setting characteristics across MDF, HDF, plywood, and particle board.',
    image: '/assets/products/lockpro-wr3-bucket.png',
    mockupImage: '/assets/products/lockpro-wr3-mockup.png',
    applications: ['Modular Furniture', 'Modular Kitchens', 'Door Manufacturing'],
    isFeatured: false,
    isAvailable: true,
  },
  {
    name: 'D2 Adhesives',
    slug: 'd2-adhesives',
    brand: 'ADHHESI PRO',
    categoryName: 'Industrial Adhesives',
    categorySlug: 'adhesives',
    shortDescription: 'Standard interior woodworking adhesive for dry area furniture and panel joinery.',
    fullDescription: 'Adhhesi Pro D2 adhesive provides stable joint bonding for indoor modular furniture, shelving, and panel assembly lines operating in controlled environments.',
    image: '/assets/products/lockpro-707.png',
    mockupImage: '/assets/products/lockpro-707.png',
    applications: ['Modular Furniture', 'Woodworking Industries'],
    isFeatured: false,
    isAvailable: true,
  },
  {
    name: 'PVC Adhesives',
    slug: 'pvc-adhesives',
    brand: 'ADHHESI PRO',
    categoryName: 'Industrial Adhesives',
    categorySlug: 'adhesives',
    shortDescription: 'Dedicated adhesive for bonding PVC foils, membranes, and sheets onto wood substrate cores.',
    fullDescription: 'Engineered for smooth application and reliable chemical adhesion between polymer surfaces (PVC sheets/membranes) and wood-based substrates.',
    image: '/assets/products/lockpro-808.png',
    mockupImage: '/assets/products/lockpro-808.png',
    applications: ['Modular Furniture', 'Modular Kitchens', 'Door Manufacturing'],
    isFeatured: false,
    isAvailable: true,
  },
  {
    name: 'Acrylic Adhesives',
    slug: 'acrylic-adhesives',
    brand: 'ADHHESI PRO',
    categoryName: 'Industrial Adhesives',
    categorySlug: 'adhesives',
    shortDescription: 'Specialized acrylic emulsion adhesive for non-porous and high-gloss panel lamination.',
    fullDescription: 'Formulated for acrylic sheet lamination, edge sealing, and multi-layer composites used in contemporary modular kitchen shutters and premium panels.',
    image: '/assets/products/lockpro-808-pr.png',
    mockupImage: '/assets/products/lockpro-808-pr.png',
    applications: ['Modular Kitchens', 'Modular Furniture', 'Panel Processing'],
    isFeatured: false,
    isAvailable: true,
  },
  {
    name: 'PUR Adhesives',
    slug: 'pur-adhesives',
    brand: 'ADHHESI PRO',
    categoryName: 'Industrial Adhesives',
    categorySlug: 'adhesives',
    shortDescription: 'Industrial polyurethane reactive hot melt and liquid systems for waterproof woodworking.',
    fullDescription: 'PUR adhesive solutions deliver zero-joint lines, extreme thermal stability, and permanent water resistance for heavy-duty edge banders and profile wrappers.',
    image: '/assets/products/lockpro-1k-pur.png',
    mockupImage: '/assets/products/lockpro-1k-pur.png',
    applications: ['Modular Kitchens', 'Modular Furniture', 'Panel Processing', 'Woodworking Industries'],
    isFeatured: false,
    isAvailable: true,
  },

  // Woodworking Tools
  {
    name: 'CNC Bits',
    slug: 'cnc-bits',
    brand: 'MODUPRO',
    categoryName: 'Woodworking Tools',
    categorySlug: 'woodworking-tools',
    shortDescription: 'Precision CNC routing, grooving, and profiling bits for panel processing and solid timber.',
    fullDescription: 'MODUPRO supplies industrial-grade CNC tooling including compression spirals, up-cut, down-cut, and profile bits designed for clean edges on melamine, ply, and MDF boards.',
    image: '',
    mockupImage: '',
    applications: ['Modular Furniture', 'Modular Kitchens', 'Woodworking Industries'],
    isFeatured: true,
    isAvailable: true,
  },
  {
    name: 'Multiboring Bits',
    slug: 'multiboring-bits',
    brand: 'MODUPRO',
    categoryName: 'Woodworking Tools',
    categorySlug: 'woodworking-tools',
    shortDescription: 'Through-hole, blind-hole, and dowel drill bits for multi-boring machinery.',
    fullDescription: 'Engineered for high-speed multi-spindle drilling machines, producing tear-free holes for 32mm system dowels, minifix cams, and shelf supports.',
    image: '',
    mockupImage: '',
    applications: ['Modular Furniture', 'Modular Kitchens', 'Woodworking Industries'],
    isFeatured: false,
    isAvailable: true,
  },
  {
    name: 'Panel Processing Tools',
    slug: 'panel-processing-tools',
    brand: 'MODUPRO',
    categoryName: 'Woodworking Tools',
    categorySlug: 'woodworking-tools',
    shortDescription: 'Specialized industrial cutterheads, scoring units, and trimmer tooling for panel lines.',
    fullDescription: 'Tooling designed for continuous automated panel sizing, tenoning, profiling, and edge finishing in modular manufacturing facilities.',
    image: '',
    mockupImage: '',
    applications: ['Modular Furniture', 'Panel Processing', 'Woodworking Industries'],
    isFeatured: false,
    isAvailable: true,
  },
  {
    name: 'TCT Panel Saw Blades',
    slug: 'tct-panel-saw-blades',
    brand: 'MODUPRO',
    categoryName: 'Woodworking Tools',
    categorySlug: 'woodworking-tools',
    shortDescription: 'Tungsten Carbide Tipped main and scoring blades for sliding table and beam panel saws.',
    fullDescription: 'High-density micro-grain carbide teeth providing chip-free cuts on pre-laminated boards, veneered panels, and solid surfaces with extended sharpening life.',
    image: '',
    mockupImage: '',
    applications: ['Modular Furniture', 'Modular Kitchens', 'Door Manufacturing', 'Woodworking Industries'],
    isFeatured: true,
    isAvailable: true,
  },
  {
    name: 'PCD Panel Saw Blades',
    slug: 'pcd-panel-saw-blades',
    brand: 'MODUPRO',
    categoryName: 'Woodworking Tools',
    categorySlug: 'woodworking-tools',
    shortDescription: 'Polycrystalline Diamond (PCD) tipped saw blades for ultra-long lifespan in panel processing.',
    fullDescription: 'Diamond tooling engineered for heavy industrial sizing lines, delivering exceptional tool longevity and zero edge chipping on abrasive laminates and compact panels.',
    image: '',
    mockupImage: '',
    applications: ['Modular Furniture', 'Door Manufacturing', 'Woodworking Industries'],
    isFeatured: false,
    isAvailable: true,
  },
  {
    name: 'Customised Tools',
    slug: 'customised-tools',
    brand: 'MODUPRO',
    categoryName: 'Woodworking Tools',
    categorySlug: 'woodworking-tools',
    shortDescription: 'Tailored tooling solutions engineered to specific workshop drawings and production requirements.',
    fullDescription: 'MODUPRO manufactures and supplies customised woodworking tooling configured to exact spindle sizes, cutting profiles, and specialized substrate requirements.',
    image: '',
    mockupImage: '',
    applications: ['Modular Furniture', 'Modular Kitchens', 'Door Manufacturing', 'Woodworking Industries'],
    isFeatured: true,
    isAvailable: true,
  },

  // Woodworking Machinery
  {
    name: 'Panel Saw',
    slug: 'panel-saw',
    brand: 'MODUPRO',
    categoryName: 'Woodworking Machinery',
    categorySlug: 'machinery',
    shortDescription: 'Precision sliding table panel saws for square, accurate sheet cutting and panel sizing.',
    fullDescription: 'Heavy-duty chassis panel saws with smooth sliding carriages, digital angle fences, and integrated scoring units for chip-free panel cutting in modular factories.',
    image: '',
    mockupImage: '',
    applications: ['Modular Furniture', 'Modular Kitchens', 'Door Manufacturing', 'Woodworking Industries'],
    isFeatured: true,
    isAvailable: true,
  },
  {
    name: 'Multi Boring Machine',
    slug: 'multi-boring-machine',
    brand: 'MODUPRO',
    categoryName: 'Woodworking Machinery',
    categorySlug: 'machinery',
    shortDescription: 'Single and multi-head drilling machinery for rapid 32mm system modular furniture production.',
    fullDescription: 'Multi-boring machines engineered for horizontal and vertical dowel drilling, hinge cup boring, and shelf pin holes with fast pneumatic positioning.',
    image: '',
    mockupImage: '',
    applications: ['Modular Furniture', 'Modular Kitchens'],
    isFeatured: false,
    isAvailable: true,
  },
  {
    name: 'Cold Press Machine',
    slug: 'cold-press-machine',
    brand: 'MODUPRO',
    categoryName: 'Woodworking Machinery',
    categorySlug: 'machinery',
    shortDescription: 'Hydraulic cold press machines for uniform lamination and flat panel pressing.',
    fullDescription: 'High-tonnage hydraulic cold presses delivering balanced pressure distribution across the entire bed for laminate bonding on ply, MDF, and blockboard.',
    image: '',
    mockupImage: '',
    applications: ['Door Manufacturing', 'Modular Furniture', 'Woodworking Industries'],
    isFeatured: false,
    isAvailable: true,
  },
  {
    name: 'Automatic Edge Bander',
    slug: 'automatic-edge-bander',
    brand: 'MODUPRO',
    categoryName: 'Woodworking Machinery',
    categorySlug: 'machinery',
    shortDescription: 'Automated continuous edge banding machine for PVC, ABS, and veneer tape application.',
    fullDescription: 'Comprehensive edge banding units featuring pre-milling, glue pot dosing, end trimming, fine top/bottom trimming, corner rounding, and scraping stations.',
    image: '',
    mockupImage: '',
    applications: ['Modular Furniture', 'Modular Kitchens', 'Woodworking Industries'],
    isFeatured: true,
    isAvailable: true,
  },
  {
    name: 'CNC Router',
    slug: 'cnc-router',
    brand: 'MODUPRO',
    categoryName: 'Woodworking Machinery',
    categorySlug: 'machinery',
    shortDescription: '3-axis and multi-axis CNC nesting and routing centers for automated sheet processing.',
    fullDescription: 'High-speed CNC routers with vacuum bed clamping, automatic tool changer (ATC), and precision linear guides for nesting, carving, and complex panel machining.',
    image: '',
    mockupImage: '',
    applications: ['Modular Furniture', 'Modular Kitchens', 'Door Manufacturing', 'Woodworking Industries'],
    isFeatured: true,
    isAvailable: true,
  },
  {
    name: 'Panel Processing Machines',
    slug: 'panel-processing-machines',
    brand: 'MODUPRO',
    categoryName: 'Woodworking Machinery',
    categorySlug: 'machinery',
    shortDescription: 'Integrated industrial machine lines for high-volume furniture and panel sizing.',
    fullDescription: 'Heavy-duty processing stations designed for synchronized cutting, grooving, edge treatment, and packaging of furniture boards.',
    image: '',
    mockupImage: '',
    applications: ['Modular Furniture', 'Panel Processing', 'Woodworking Industries'],
    isFeatured: false,
    isAvailable: true,
  },
  {
    name: 'Edge Banding Machines',
    slug: 'edge-banding-machines',
    brand: 'MODUPRO',
    categoryName: 'Woodworking Machinery',
    categorySlug: 'machinery',
    shortDescription: 'Manual, semi-automatic, and curved edge banders for diverse workshop workflows.',
    fullDescription: 'Versatile edge banding equipment capable of handling straight and contoured shapes with precise hot-melt adhesive application.',
    image: '',
    mockupImage: '',
    applications: ['Modular Furniture', 'Modular Kitchens', 'Woodworking Industries'],
    isFeatured: false,
    isAvailable: true,
  },
  {
    name: 'Cold / Hot Press Machines',
    slug: 'cold-hot-press-machines',
    brand: 'MODUPRO',
    categoryName: 'Woodworking Machinery',
    categorySlug: 'machinery',
    shortDescription: 'Thermal and ambient press machinery for plywood, door manufacturing, and veneer lamination.',
    fullDescription: 'Industrial heated platen and ambient hydraulic presses ensuring controlled temperature and pressure cycles for door cores and architectural panels.',
    image: '',
    mockupImage: '',
    applications: ['Door Manufacturing', 'Woodworking Industries', 'Modular Furniture'],
    isFeatured: false,
    isAvailable: true,
  },

  // Machine Spares
  {
    name: 'Woodworking Machine Spares',
    slug: 'woodworking-machine-spares',
    brand: 'MODUPRO',
    categoryName: 'Machine Spares',
    categorySlug: 'machine-spares',
    shortDescription: 'Direct-fit replacement spare parts for panel saws, edge banders, CNC routers, and boring machines.',
    fullDescription: 'MODUPRO maintains an inventory of essential spares including feed rollers, glue pots, belts, pneumatic cylinders, linear bearings, and cutter arbor components.',
    image: '',
    mockupImage: '',
    applications: ['Modular Furniture', 'Panel Processing', 'Woodworking Industries'],
    isFeatured: true,
    isAvailable: true,
  },
  {
    name: 'Mechanical Spares & Components',
    slug: 'mechanical-spares-components',
    brand: 'MODUPRO',
    categoryName: 'Machine Spares',
    categorySlug: 'machine-spares',
    shortDescription: 'High-wear mechanical components: bearings, drive gears, guide rails, and clamping units.',
    fullDescription: 'Precision replacement components engineered to restore machine tolerances, alignment, and smooth operation under demanding factory duty cycles.',
    image: '',
    mockupImage: '',
    applications: ['Woodworking Industries', 'Panel Processing'],
    isFeatured: false,
    isAvailable: true,
  },
  {
    name: 'Electrical Spares & Controls',
    slug: 'electrical-spares-controls',
    brand: 'MODUPRO',
    categoryName: 'Machine Spares',
    categorySlug: 'machine-spares',
    shortDescription: 'Sensors, limit switches, contactors, heating elements, and thermostat units.',
    fullDescription: 'Certified electrical parts for machinery control panels, heating chambers on edge banders, and motor drive systems.',
    image: '',
    mockupImage: '',
    applications: ['Woodworking Industries', 'Panel Processing'],
    isFeatured: false,
    isAvailable: true,
  },
  {
    name: 'Computerized & CNC Spares',
    slug: 'computerized-cnc-spares',
    brand: 'MODUPRO',
    categoryName: 'Machine Spares',
    categorySlug: 'machine-spares',
    shortDescription: 'Encoders, servo drives, PLC controllers, and HMI display screen replacements.',
    fullDescription: 'Original specification computerized automation spares to troubleshoot and resolve motion control faults on CNC machines and automated lines.',
    image: '',
    mockupImage: '',
    applications: ['Woodworking Industries', 'Panel Processing'],
    isFeatured: false,
    isAvailable: true,
  },

  // PVC Edge Banding & Hardware
  {
    name: 'PVC Edge Banding Tapes',
    slug: 'pvc-edge-banding-tapes',
    brand: 'MODUPRO',
    categoryName: 'PVC Edge Banding & Hardware',
    categorySlug: 'edge-banding-hardware',
    shortDescription: 'High-grade PVC edge banding tapes available in solid colors, wood grains, and textures.',
    fullDescription: 'Formulated with high-impact polymer for uniform flexibility, clean trimming, and solid primer backing that ensures seamless adhesion with MODUPRO adhesives.',
    image: '',
    mockupImage: '',
    applications: ['Modular Furniture', 'Modular Kitchens', 'Door Manufacturing'],
    isFeatured: true,
    isAvailable: true,
  },
  {
    name: '2D Hinges',
    slug: '2d-hinges',
    brand: 'MODUPRO',
    categoryName: 'PVC Edge Banding & Hardware',
    categorySlug: 'edge-banding-hardware',
    shortDescription: 'Standard two-dimensional adjustable concealed hinges for modular cabinet doors.',
    fullDescription: 'Engineered for smooth movement, reliable door alignment, and durable cycle life across modular furniture units.',
    image: '',
    mockupImage: '',
    applications: ['Modular Furniture', 'Modular Kitchens'],
    isFeatured: false,
    isAvailable: true,
  },
  {
    name: '3D Hinges',
    slug: '3d-hinges',
    brand: 'MODUPRO',
    categoryName: 'PVC Edge Banding & Hardware',
    categorySlug: 'edge-banding-hardware',
    shortDescription: 'Three-way adjustable soft-closing hinges for precision furniture door installations.',
    fullDescription: 'Provides height, depth, and side adjustments with integrated hydraulic damping for silent closing in modular kitchens and wardrobes.',
    image: '',
    mockupImage: '',
    applications: ['Modular Furniture', 'Modular Kitchens'],
    isFeatured: true,
    isAvailable: true,
  },
  {
    name: 'Telescopic Channels',
    slug: 'telescopic-channels',
    brand: 'MODUPRO',
    categoryName: 'PVC Edge Banding & Hardware',
    categorySlug: 'edge-banding-hardware',
    shortDescription: 'Heavy-duty ball bearing telescopic drawer slides for smooth drawer extension.',
    fullDescription: 'Precision steel ball runner channels engineered for smooth gliding, high load ratings, and long-term durability in modular drawer units.',
    image: '',
    mockupImage: '',
    applications: ['Modular Furniture', 'Modular Kitchens'],
    isFeatured: false,
    isAvailable: true,
  },
  {
    name: 'CAM (Eccentric Connecting Fittings)',
    slug: 'cam-fittings',
    brand: 'MODUPRO',
    categoryName: 'PVC Edge Banding & Hardware',
    categorySlug: 'edge-banding-hardware',
    shortDescription: 'Minifix cam locks for KD (knock-down) modular panel joinery and cabinet assembly.',
    fullDescription: 'Die-cast zinc cam connectors for rigid 90-degree panel joints in flat-pack and modular furniture production.',
    image: '',
    mockupImage: '',
    applications: ['Modular Furniture', 'Modular Kitchens'],
    isFeatured: false,
    isAvailable: true,
  },
  {
    name: 'Nylon Bush',
    slug: 'nylon-bush',
    brand: 'MODUPRO',
    categoryName: 'PVC Edge Banding & Hardware',
    categorySlug: 'edge-banding-hardware',
    shortDescription: 'Durable nylon expansion bushes and dowel sleeves for secure hardware fastening.',
    fullDescription: 'High-strength nylon inserts providing vibration dampening and reinforced screw retention in particle board and MDF panels.',
    image: '',
    mockupImage: '',
    applications: ['Modular Furniture', 'Modular Kitchens'],
    isFeatured: false,
    isAvailable: true,
  },
  {
    name: 'Bolt & Assembly Hardware',
    slug: 'bolt-assembly-hardware',
    brand: 'MODUPRO',
    categoryName: 'PVC Edge Banding & Hardware',
    categorySlug: 'edge-banding-hardware',
    shortDescription: 'Connecting bolts, dowels, and structural hardware for knockdown furniture assembly.',
    fullDescription: 'Precision-threaded connecting bolts compatible with standard CAM systems for sturdy modular cabinetry and furniture assembly.',
    image: '',
    mockupImage: '',
    applications: ['Modular Furniture', 'Modular Kitchens'],
    isFeatured: false,
    isAvailable: true,
  },
];

export const servicesData = [
  {
    serviceNumber: '01',
    name: 'Machine Installation',
    slug: 'machine-installation',
    shortDescription: 'Professional on-site installation and alignment support for woodworking machinery.',
    fullDescription: 'MODUPRO provides trained service engineers for the on-site installation, leveling, initial wiring, and calibration of panel saws, edge banders, multi-boring machines, and CNC systems.',
    handledComponents: ['Mechanical', 'Electrical', 'Computerized'],
    scope: [
      'Site readiness verification and leveling',
      'Mechanical positioning and assembly',
      'Electrical connection and control panel checks',
      'Initial trial cuts and parameter verification',
    ],
    applicableMachinery: ['Panel Saw', 'Automatic Edge Bander', 'CNC Router', 'Multi Boring Machine', 'Cold/Hot Press'],
  },
  {
    serviceNumber: '02',
    name: 'Machine Maintenance',
    slug: 'machine-maintenance',
    shortDescription: 'Preventive and scheduled maintenance support for woodworking equipment.',
    fullDescription: 'Structured maintenance routines to prevent unexpected downtime, maintain cutting precision, ensure proper lubrication, and extend the operating life of workshop machinery.',
    handledComponents: ['Mechanical', 'Electrical'],
    scope: [
      'Guideway and carriage inspection',
      'Lubrication and pneumatic pressure verification',
      'Glue tank cleanout and temperature calibration',
      'Spindle runout and bearing check',
    ],
    applicableMachinery: ['Panel Saw', 'Edge Banding Machines', 'CNC Routers', 'Cold Press'],
  },
  {
    serviceNumber: '03',
    name: 'Machine Troubleshooting',
    slug: 'machine-troubleshooting',
    shortDescription: 'Fast diagnostic and troubleshooting support for woodworking machinery operational faults.',
    fullDescription: 'Expert diagnostic assistance to identify and isolate issues causing cutting defects, edge banding adhesion failures, electrical trips, or machine positioning errors.',
    handledComponents: ['Mechanical', 'Electrical', 'Computerized'],
    scope: [
      'Operational error analysis',
      'Sensors, encoders, and limit switch verification',
      'Glue pot temperature and feed synchronization review',
      'Pneumatic and hydraulic pressure diagnostics',
    ],
    applicableMachinery: ['Automatic Edge Bander', 'CNC Router', 'Panel Saw', 'Multi Boring'],
  },
  {
    serviceNumber: '04',
    name: 'Mechanical Repair',
    slug: 'mechanical-repair',
    shortDescription: 'Repair and overhaul of mechanical machine components, drives, and assemblies.',
    fullDescription: 'Service support for mechanical components of woodworking machines including arbor shafts, gearboxes, feed rollers, bearing replacements, and carriage guide re-alignment.',
    handledComponents: ['Mechanical'],
    scope: [
      'Spindle and arbor bearing replacement',
      'Drive chain and belt tension adjustment',
      'Feed track and pressure roller reconditioning',
      'Bed leveling and sliding table realignments',
    ],
    applicableMachinery: ['Sliding Table Panel Saw', 'Edge Bander', 'Cold Press', 'Multi Boring'],
  },
  {
    serviceNumber: '05',
    name: 'Electrical Repair',
    slug: 'electrical-repair',
    shortDescription: 'Repair and service of electrical components, heating circuits, and motor controls.',
    fullDescription: 'Service and repair of electrical subsystems including contactors, relays, heating elements, thermostatic controllers, motor starters, and wiring harnesses.',
    handledComponents: ['Electrical'],
    scope: [
      'Control panel rewiring and component renewal',
      'Heating element and sensor replacements',
      'Motor diagnostics and overload protection setup',
      'Safety interlock and emergency stop testing',
    ],
    applicableMachinery: ['Edge Banding Machines', 'Panel Saw', 'Press Machinery', 'CNC Router'],
  },
  {
    serviceNumber: '06',
    name: 'Computerized System Service',
    slug: 'computerized-system-service',
    shortDescription: 'Service and troubleshooting of computerized and CNC machine components.',
    fullDescription: 'Troubleshooting and calibration of computerized machine controllers, CNC axis drivers, PLC units, encoder feedbacks, and digital operator interfaces.',
    handledComponents: ['Computerized'],
    scope: [
      'PLC and numerical controller diagnostics',
      'Servo driver and stepper motor configuration',
      'HMI screen and input terminal troubleshooting',
      'Origin calibration and software parameter backups',
    ],
    applicableMachinery: ['CNC Router', 'Automatic Edge Bander', 'Panel Processing Machines'],
  },
  {
    serviceNumber: '07',
    name: 'Machine Spares Supply',
    slug: 'machine-spares-supply',
    shortDescription: 'Supply of original and compatible spare parts for woodworking machines.',
    fullDescription: 'MODUPRO supplies verified spare parts for panel processing machines to minimize downtime and preserve machine longevity.',
    handledComponents: ['Mechanical', 'Electrical', 'Computerized'],
    scope: [
      'Direct part identification from machine specifications',
      'Supply of high-wear mechanical and electrical parts',
      'Guidance on correct part installation and calibration',
    ],
    applicableMachinery: ['Panel Saw', 'Multi Boring', 'Edge Bander', 'CNC Router', 'Presses'],
  },
  {
    serviceNumber: '08',
    name: 'Woodworking Machine Service',
    slug: 'woodworking-machine-service',
    shortDescription: 'Full-spectrum service support for woodworking machines and plant equipment.',
    fullDescription: 'Comprehensive workshop service packages covering mechanical, electrical, and computerized machinery requirements to keep your manufacturing facility producing at full potential.',
    handledComponents: ['Mechanical', 'Electrical', 'Computerized'],
    scope: [
      'Complete workshop machinery audit',
      'Preventive servicing schedule planning',
      'Emergency breakdown response',
      'Operator machine handling guidance',
    ],
    applicableMachinery: ['All woodworking and panel processing machinery'],
  },
];

export const industriesData = [
  {
    name: 'Modular Furniture',
    slug: 'modular-furniture',
    description: 'Comprehensive solutions for modular wardrobe, workstation, and cabinet manufacturing units.',
    solutionsOffered: [
      'PVAC white glue and D2/D3 adhesives for carcass and joinery bonding',
      'TCT and PCD panel saw blades for chip-free melamine and particle board sizing',
      'Multiboring bits and CNC tooling for precise 32mm system drilling',
      'PVC edge banding tapes, CAM fittings, and telescopic channels',
      'Machine maintenance and installation for edge banders and panel saws',
    ],
    commonApplications: [
      'Office modular workstations and storage',
      'Residential wardrobes, beds, and study tables',
      'Flat-pack and knock-down furniture assembly',
      'Post-formed and edge-banded panel elements',
    ],
    applicableProducts: [
      'Lockpro WR 3 (D3)',
      'Lockpro 808',
      'PVAC White Glue',
      'Automatic Edge Bander',
      'TCT Panel Saw Blades',
      'PVC Edge Banding Tapes',
      '3D Hinges',
    ],
  },
  {
    name: 'Modular Kitchens',
    slug: 'modular-kitchens',
    description: 'Moisture-resistant adhesive systems, precision tooling, and hardware for modern modular kitchens.',
    solutionsOffered: [
      'Certified D3 and PUR water-resistant adhesives for damp kitchen environments',
      'Acrylic and PVC adhesives for high-gloss shutter lamination',
      'CNC routing bits for decorative shutter profiles and handle grooves',
      '3D adjustable soft-close hinges and corrosion-resistant hardware',
      'Troubleshooting and servicing for continuous edge banding lines',
    ],
    commonApplications: [
      'Base and overhead kitchen cabinet carcasses',
      'Water-exposed sink and countertop base units',
      'Acrylic, laminate, and membrane finish kitchen shutters',
      'Drawer pull-out boxes and hardware fitting',
    ],
    applicableProducts: [
      'Lockpro VUS PUR Adhesives',
      'Lockpro WR 3 (D3)',
      'Certified D3 Adhesives',
      'Acrylic Adhesives',
      '3D Hinges',
      'CNC Bits',
      'Edge Banding Machines',
    ],
  },
  {
    name: 'Door Manufacturing',
    slug: 'door-manufacturing',
    description: 'Heavy-duty bonding adhesives, press machinery, and sizing blades for flush and laminated doors.',
    solutionsOffered: [
      'High-strength D3 and PVAC adhesives for door core and face lamination',
      'Cold press and heated press machinery for uniform platen bonding',
      'Heavy-duty panel saw blades for door sizing and rebating',
      'Customised cutter tooling for door lock recesses and hinge pockets',
      'Mechanical and electrical service support for press machinery',
    ],
    commonApplications: [
      'Flush door internal frame and skin pressing',
      'Laminated and decorative membrane door manufacturing',
      'Solid core wooden doors and engineered stiles',
      'Acoustic and commercial interior doors',
    ],
    applicableProducts: [
      'Lockpro WR 3 (D3)',
      'PVAC White Glue',
      'Cold Press Machine',
      'Cold/Hot Press Machines',
      'TCT Panel Saw Blades',
      'Customised Tools',
    ],
  },
  {
    name: 'Woodworking Industries',
    slug: 'woodworking-industries',
    description: 'End-to-end tooling, machinery, service, and adhesives for commercial panel processing and timber mills.',
    solutionsOffered: [
      'Full spectrum of industrial adhesives: PVAC, D2, D3, PUR, and contact formulations',
      'Standard and customised woodworking cutting tools and diamond PCD blades',
      'Panel processing machines, CNC routers, and multi-boring equipment',
      'Original mechanical, electrical, and computerized machine spares',
      'Certified technician support for machine installation, troubleshooting, and repairs',
    ],
    commonApplications: [
      'Plywood and board lamination mills',
      'Commercial architectural woodwork and joinery',
      'Solid timber sizing and profiling operations',
      'Industrial panel cutting and nesting plants',
    ],
    applicableProducts: [
      'Lockpro VUS PUR Adhesives',
      'Lockpro 808 PR',
      'LockPro 707',
      'Panel Saw',
      'CNC Router',
      'Woodworking Machine Spares',
      'Machine Maintenance Service',
    ],
  },
];

export const seedDatabase = async () => {
  try {
    const mongoUri = process.env.MONGODB_URI || 'mongodb://127.0.0.1:27017/modupro_db';
    if (mongoose.connection.readyState === 0) {
      await mongoose.connect(mongoUri);
    }

    console.log('[Seed]: Clearing existing collections...');
    await ProductCategory.deleteMany({});
    await Product.deleteMany({});
    await Service.deleteMany({});
    await Industry.deleteMany({});

    console.log('[Seed]: Inserting categories...');
    await ProductCategory.insertMany(categoriesData);

    console.log('[Seed]: Inserting products...');
    await Product.insertMany(productsData);

    console.log('[Seed]: Inserting services...');
    await Service.insertMany(servicesData);

    console.log('[Seed]: Inserting industries...');
    await Industry.insertMany(industriesData);

    console.log('[Seed]: Database successfully populated with verified MODUPRO profile data.');
    return true;
  } catch (err) {
    console.error('[Seed Error]:', err.message);
    return false;
  }
};

// If run directly from CLI
if (process.argv[1]?.endsWith('seedData.js')) {
  seedDatabase().then(() => {
    mongoose.disconnect();
    process.exit(0);
  });
}
