import mongoose from 'mongoose';
import dotenv from 'dotenv';
import { ProductCategory } from '../models/ProductCategory.js';
import { Product } from '../models/Product.js';
import { Service } from '../models/Service.js';
import { Industry } from '../models/Industry.js';

dotenv.config();

export const categoriesData = [
  {
    name: '1. Adhhesi pro',
    slug: 'adhhesi-pro',
    description: 'Manufacturing of PVAC white glue established in 2015. Supplying Certified D3, Commercial D3, D2, PVC/Acrylic Adhesives, PUR Adhesives, and Lockpro Range.',
    displayOrder: 1,
  },
  {
    name: '2. Wood working tools',
    slug: 'woodworking-tools',
    description: 'Sales and Service of Woodworking Tools: CNC Bits, Multiboring Bits, Panel Processing Tools, Panel Saw Blades (TCT & PCD), and Customised Tools.',
    displayOrder: 2,
  },
  {
    name: '3. Panel processing machines',
    slug: 'panel-processing-machines',
    description: 'Supplying heavy-duty industrial machines: Panel Saw, Multi Boring, Cold Press, Automatic Edge Bander, CNC Router, and Cold/Hot Press Machines.',
    displayOrder: 3,
  },
  {
    name: '4. PVC edge banding tapes and hardware',
    slug: 'pvc-edge-banding-hardware',
    description: 'Trading of PVC Edge Banding Tapes, 2D-3D Hinges, Telescopic Channels, 6 GMS CAM, Nylon Bush, and Bolt.',
    displayOrder: 4,
  },
  {
    name: '5. Panel processing machines, and its spares',
    slug: 'machine-spares-services',
    description: 'Service of wood working Machines & Sales of Spares of all makes. Service Engineers installing, maintaining, troubleshooting, and repairing mechanical, electrical, and computerized components.',
    displayOrder: 5,
  },
];

export const productsData = [
  // ===========================================================================
  // SUB-CATEGORY 1: ADHHESI PRO (EST. 2015)
  // ===========================================================================
  {
    name: 'PVAC White Glue',
    slug: 'pvac-white-glue',
    brand: 'ADHHESI PRO',
    categoryName: 'Adhhesi pro',
    categorySlug: 'adhhesi-pro',
    shortDescription: 'Core polyvinyl acetate white glue manufactured since 2015 for modular furniture, kitchens, door manufacturers, and woodworking industries.',
    fullDescription: 'MODUPRO INNOVATION manufactures and trades PVAC White Glue under the Adhhesi Pro brand. Established in 2015, this formulation delivers reliable bonding for modular furniture, modular kitchens, door manufacturers, and woodworking industries.',
    image: '/assets/products/Adhhesi pro/WR 3 Bucket.png',
    mockupImage: '/assets/products/Adhhesi pro/WR 3 MOCKUP@4x-8.png',
    badge: 'Manufacturing Since 2015',
    applications: ['Modular furniture', 'Modular Kitchens', 'Doors Manufacturer', 'Wood Working industries'],
    features: [
      'Manufacturing & Trading of PVAC White Glue established in 2015',
      'Supplied to modular furniture, modular kitchens, door manufacturers',
      'High bond integrity across particle board, MDF, and plywood',
      'Water-based, clean application formulation',
    ],
    isFeatured: true,
    isAvailable: true,
  },
  {
    name: 'Certified D3 Adhesives',
    slug: 'certified-d3-adhesives',
    brand: 'ADHHESI PRO',
    categoryName: 'Adhhesi pro',
    categorySlug: 'adhhesi-pro',
    shortDescription: 'Water-resistant certified D3 adhesive formulation for demanding exterior-facing interior joinery.',
    fullDescription: 'Certified D3 grade adhesive engineered to resist high ambient humidity and water contact, ideal for modular kitchens, bathroom vanities, and door lamination.',
    image: '/assets/products/Adhhesi pro/WR 3 Bucket.png',
    mockupImage: '/assets/products/Adhhesi pro/WR 3 MOCKUP@4x-8.png',
    badge: 'Certified D3',
    applications: ['Modular Kitchens', 'Doors Manufacturer', 'Wood Working industries'],
    features: [
      'Certified D3 water resistance classification',
      'Resists intermittent water exposure and moisture in modular kitchens',
      'High bonding strength across timber and composite panels',
      'Supplied in industrial pails and drums',
    ],
    isFeatured: true,
    isAvailable: true,
  },
  {
    name: 'Commercial D3 Adhesives',
    slug: 'commercial-d3-adhesives',
    brand: 'ADHHESI PRO',
    categoryName: 'Adhhesi pro',
    categorySlug: 'adhhesi-pro',
    shortDescription: 'Cost-effective commercial D3 adhesive balancing moisture resistance and production efficiency.',
    fullDescription: 'Formulated for standard industrial production runs requiring D3 moisture protection with dependable setting characteristics across MDF, HDF, plywood, and particle board.',
    image: '/assets/products/Adhhesi pro/WR 3 Bucket.png',
    mockupImage: '/assets/products/Adhhesi pro/WR 3 MOCKUP@4x-8.png',
    badge: 'Commercial D3',
    applications: ['Modular furniture', 'Modular Kitchens', 'Doors Manufacturer'],
    features: [
      'Balanced open time for factory production runs',
      'Commercial D3 moisture tolerance',
      'Consistent viscosity for manual or roller application',
    ],
    isFeatured: false,
    isAvailable: true,
  },
  {
    name: 'D2 Adhesives',
    slug: 'd2-adhesives',
    brand: 'ADHHESI PRO',
    categoryName: 'Adhhesi pro',
    categorySlug: 'adhhesi-pro',
    shortDescription: 'Standard interior woodworking adhesive for dry area modular furniture and panel joinery.',
    fullDescription: 'Adhhesi Pro D2 adhesive provides stable joint bonding for indoor modular furniture, shelving, and panel assembly lines operating in controlled environments.',
    image: '/assets/products/Adhhesi pro/707 MOCKUP@4x-8.png',
    mockupImage: '/assets/products/Adhhesi pro/707 MOCKUP@4x-8.png',
    badge: 'D2 Formulation',
    applications: ['Modular furniture', 'Wood Working industries'],
    features: [
      'Standard interior wood bonding',
      'Rapid tack and quick grab on porous wood substrates',
      'Smooth spreadability for workshop joinery',
    ],
    isFeatured: false,
    isAvailable: true,
  },
  {
    name: 'PVC / Acrylic Adhesives',
    slug: 'pvc-acrylic-adhesives',
    brand: 'ADHHESI PRO',
    categoryName: 'Adhhesi pro',
    categorySlug: 'adhhesi-pro',
    shortDescription: 'Dedicated adhesive for bonding PVC foils, membranes, and acrylic sheets onto wood substrate cores.',
    fullDescription: 'Engineered for smooth application and reliable chemical adhesion between polymer surfaces (PVC sheets/membranes/acrylics) and wood-based substrate cores.',
    image: '/assets/products/Adhhesi pro/808 MOCKUP@4x-8.png',
    mockupImage: '/assets/products/Adhhesi pro/808 MOCKUP@4x-8.png',
    badge: 'PVC & Acrylic',
    applications: ['Modular furniture', 'Modular Kitchens', 'Doors Manufacturer'],
    features: [
      'Strong peel resistance against edge lifting',
      'Formulated for acrylic sheets and PVC membrane pressing',
      'Clean film formation without telegraphing',
    ],
    isFeatured: false,
    isAvailable: true,
  },
  {
    name: 'PUR Adhesives',
    slug: 'pur-adhesives',
    brand: 'ADHHESI PRO',
    categoryName: 'Adhhesi pro',
    categorySlug: 'adhhesi-pro',
    shortDescription: 'Industrial polyurethane reactive hot melt and liquid systems for waterproof woodworking.',
    fullDescription: 'PUR adhesive solutions deliver zero-joint lines, extreme thermal stability, and permanent water resistance for heavy-duty edge banders and profile wrappers.',
    image: '/assets/products/Adhhesi pro/1k pur png.png',
    mockupImage: '/assets/products/Adhhesi pro/1k pur png.png',
    badge: 'PUR Formulation',
    applications: ['Modular Kitchens', 'Modular furniture', 'Doors Manufacturer', 'Wood Working industries'],
    features: [
      'Polyurethane reactive chemistry for permanent water resistance',
      'Zero visible glue line on edge-banded modular panels',
      'Superior thermal and humidity resistance',
    ],
    isFeatured: true,
    isAvailable: true,
  },
  {
    name: 'Lockpro VUS PUR Adhesives',
    slug: 'lockpro-vus-pur-adhesives',
    brand: 'LOCKPRO',
    categoryName: 'Adhhesi pro',
    categorySlug: 'adhhesi-pro',
    shortDescription: 'Industrial reactive polyurethane (PUR) adhesive engineered for panel processing and edge banding.',
    fullDescription: 'Lockpro VUS PUR Adhesives are formulated for high-performance bonding in modular furniture and industrial woodworking. Engineered for extreme moisture and heat resistance during continuous production lines.',
    image: '/assets/products/Adhhesi pro/1k pur png.png',
    mockupImage: '/assets/products/Adhhesi pro/1k pur png.png',
    badge: 'Lockpro PUR',
    applications: ['Modular furniture', 'Modular Kitchens', 'Wood Working industries'],
    features: [
      'High-performance PUR reactive chemistry',
      'Extreme water and heat barrier on modular joints',
      'Supplied for high-speed edge banding and lamination lines',
    ],
    isFeatured: true,
    isAvailable: true,
  },
  {
    name: 'Lockpro WR 3 (D3)',
    slug: 'lockpro-wr-3-d3',
    brand: 'LOCKPRO',
    categoryName: 'Adhhesi pro',
    categorySlug: 'adhhesi-pro',
    shortDescription: 'Water-resistant D3 grade white adhesive for modular furniture, kitchens, and door manufacturing.',
    fullDescription: 'Lockpro WR 3 (D3) is an advanced water-resistant emulsion adhesive specially developed for woodworking environments where moisture protection and dependable bonding are vital.',
    image: '/assets/products/Adhhesi pro/WR 3 Bucket.png',
    mockupImage: '/assets/products/Adhhesi pro/WR 3 MOCKUP@4x-8.png',
    badge: 'Lockpro WR 3 (D3)',
    applications: ['Modular Kitchens', 'Doors Manufacturer', 'Modular furniture', 'Wood Working industries'],
    features: [
      'D3 water resistance classification',
      'Advanced wood joint bonding integrity',
      'Supplied in industrial pails and drums',
    ],
    isFeatured: true,
    isAvailable: true,
  },
  {
    name: 'Lockpro 808',
    slug: 'lockpro-808',
    brand: 'LOCKPRO',
    categoryName: 'Adhhesi pro',
    categorySlug: 'adhhesi-pro',
    shortDescription: 'Heavy-duty industrial adhesive formulation for demanding woodworking and surface lamination.',
    fullDescription: 'Lockpro 808 is designed for rapid tack, high bond integrity, and consistent application across wood, composite panels, and laminate bonding lines.',
    image: '/assets/products/Adhhesi pro/808 MOCKUP@4x-8.png',
    mockupImage: '/assets/products/Adhhesi pro/808 MOCKUP@4x-8.png',
    badge: 'Lockpro 808',
    applications: ['Modular furniture', 'Doors Manufacturer', 'Wood Working industries'],
    features: [
      'High solids formulation with rapid green strength',
      'Quick bond grab on composite panels and timber',
      'Consistent batch quality',
    ],
    isFeatured: true,
    isAvailable: true,
  },
  {
    name: 'Lockpro 808 PR',
    slug: 'lockpro-808-pr',
    brand: 'LOCKPRO',
    categoryName: 'Adhhesi pro',
    categorySlug: 'adhhesi-pro',
    shortDescription: 'High-performance adhesive primer and bonding agent for panel manufacturing lines.',
    fullDescription: 'Lockpro 808 PR offers enhanced bond strength and chemical stability for heavy industrial processing, modular shutter fabrication, and multi-substrate applications.',
    image: '/assets/products/Adhhesi pro/808 pr png.png',
    mockupImage: '/assets/products/Adhhesi pro/808 pr png.png',
    badge: 'Lockpro 808 PR',
    applications: ['Modular furniture', 'Doors Manufacturer', 'Wood Working industries'],
    features: [
      'Industrial PR grade bonding agent',
      'Reinforced chemical grab across difficult substrates',
      'Ideal for heavy modular shutter manufacturing',
    ],
    isFeatured: true,
    isAvailable: true,
  },
  {
    name: 'LockPro 707',
    slug: 'lockpro-707',
    brand: 'LOCKPRO',
    categoryName: 'Adhhesi pro',
    categorySlug: 'adhhesi-pro',
    shortDescription: 'Specialty woodworking adhesive for assembly bonding, edge banding, and joinery.',
    fullDescription: 'LockPro 707 provides reliable joint retention, clean handling, and balanced open time for assembly shops, modular cabinetmakers, and timber joinery.',
    image: '/assets/products/Adhhesi pro/707 MOCKUP@4x-8.png',
    mockupImage: '/assets/products/Adhhesi pro/707 MOCKUP@4x-8.png',
    badge: 'LockPro 707',
    applications: ['Modular furniture', 'Modular Kitchens', 'Wood Working industries'],
    features: [
      'Specialized joinery formulation',
      'Clean film formation after curing',
      'Balanced open time for cabinet shops',
    ],
    isFeatured: true,
    isAvailable: true,
  },

  // ===========================================================================
  // SUB-CATEGORY 2: WOOD WORKING TOOLS (EDGE BANDING, CNC, PANEL SAW, COLD/HOT PRESS)
  // ===========================================================================
  {
    name: 'CNC Bits',
    slug: 'cnc-bits',
    brand: 'MODUPRO',
    categoryName: 'Wood working tools',
    categorySlug: 'woodworking-tools',
    shortDescription: 'Precision CNC routing, grooving, and profiling bits for panel processing and solid timber.',
    fullDescription: 'MODUPRO is a leading supplier of woodworking tools. We supply industrial CNC bits including compression spirals, up-cut, down-cut, and custom profiling bits designed for chip-free cuts on melamine, MDF, and plywood.',
    image: '/assets/products/Woodworking Tools/4c6e378e-3b05-4e8f-b71e-bf83d9989023-Photoroom.png',
    mockupImage: '/assets/products/Woodworking Tools/4c6e378e-3b05-4e8f-b71e-bf83d9989023-Photoroom.png',
    badge: 'CNC Bits',
    applications: ['Modular furniture', 'Modular Kitchens', 'Wood Working industries'],
    features: [
      'Micro-grain solid carbide construction',
      'Compression spiral geometry for chip-free top and bottom edges',
      'Balanced for high-RPM machine spindles',
    ],
    isFeatured: true,
    isAvailable: true,
  },
  {
    name: 'Multiboring Bits',
    slug: 'multiboring-bits',
    brand: 'MODUPRO',
    categoryName: 'Wood working tools',
    categorySlug: 'woodworking-tools',
    shortDescription: 'Through-hole, blind-hole, and dowel drill bits for multi-boring machinery.',
    fullDescription: 'Engineered for multi-boring machines for modular furniture manufacturing, producing tear-free holes for 32mm system dowels, minifix cams, and shelf supports.',
    image: '/assets/products/Woodworking Tools/4c6e378e-3b05-4e8f-b71e-bf83d9989023-Photoroom.png',
    mockupImage: '/assets/products/Woodworking Tools/4c6e378e-3b05-4e8f-b71e-bf83d9989023-Photoroom.png',
    badge: 'Multiboring Bits',
    applications: ['Modular furniture', 'Modular Kitchens', 'Wood Working industries'],
    features: [
      'Right-hand (black) and left-hand (orange) rotation sets',
      'Hardened steel body with micro-fine carbide spur tips',
      'Clean entry and exit holes without laminate blowouts',
    ],
    isFeatured: true,
    isAvailable: true,
  },
  {
    name: 'Panel Processing Tools',
    slug: 'panel-processing-tools',
    brand: 'MODUPRO',
    categoryName: 'Wood working tools',
    categorySlug: 'woodworking-tools',
    shortDescription: 'Specialized industrial cutterheads, scoring units, and trimmer tooling for panel processing lines.',
    fullDescription: 'Tooling designed for continuous automated panel sizing, tenoning, profiling, and edge finishing in modular manufacturing facilities.',
    image: '/assets/products/Woodworking Tools/4c6e378e-3b05-4e8f-b71e-bf83d9989023-Photoroom.png',
    mockupImage: '/assets/products/Woodworking Tools/4c6e378e-3b05-4e8f-b71e-bf83d9989023-Photoroom.png',
    badge: 'Panel Processing Tools',
    applications: ['Modular furniture', 'Wood Working industries'],
    features: [
      'Pre-milling cutterheads for edge banders',
      'Radius scrapers and fine trimmer cutters',
      'Replaceable carbide knives for rapid changeover',
    ],
    isFeatured: false,
    isAvailable: true,
  },
  {
    name: 'Panel Saw Blades (TCT & PCD)',
    slug: 'panel-saw-blades-tct-pcd',
    brand: 'MODUPRO',
    categoryName: 'Wood working tools',
    categorySlug: 'woodworking-tools',
    shortDescription: 'Tungsten Carbide Tipped (TCT) and Polycrystalline Diamond (PCD) main & scoring saw blades.',
    fullDescription: 'We supply high-density TCT and PCD panel saw blades for sliding table panel saws and beam saws. Laser-cut bodies with expansion slots ensure chip-free cuts on pre-laminated boards and veneers.',
    image: '/assets/products/Woodworking Tools/c59e4c06-c6c5-4eee-8713-2b9bfe24b9cb-Photoroom.png',
    mockupImage: '/assets/products/Woodworking Tools/c59e4c06-c6c5-4eee-8713-2b9bfe24b9cb-Photoroom.png',
    badge: 'TCT & PCD Blades',
    applications: ['Modular furniture', 'Doors Manufacturer', 'Wood Working industries'],
    features: [
      'Main blade paired with conical scoring blade',
      'Triple-chip grind (TCG) for chip-free cuts on double-sided laminates',
      'PCD diamond options for extended sharpening life',
    ],
    isFeatured: true,
    isAvailable: true,
  },
  {
    name: 'Customised Woodworking Tools',
    slug: 'customised-woodworking-tools',
    brand: 'MODUPRO',
    categoryName: 'Wood working tools',
    categorySlug: 'woodworking-tools',
    shortDescription: 'Tailored tooling solutions engineered to specific workshop drawings and production profiles.',
    fullDescription: 'MODUPRO is a leading supplier of customised woodworking tools. We manufacture custom router bits, shaper cutters, and saw blades configured to exact customer drawings and spindle dimensions.',
    image: '/assets/products/Woodworking Tools/4c6e378e-3b05-4e8f-b71e-bf83d9989023-Photoroom.png',
    mockupImage: '/assets/products/Woodworking Tools/4c6e378e-3b05-4e8f-b71e-bf83d9989023-Photoroom.png',
    badge: 'Customised Tools',
    applications: ['Modular furniture', 'Modular Kitchens', 'Doors Manufacturer', 'Wood Working industries'],
    features: [
      'Manufactured as per workshop drawings or sample profiles',
      'Custom bore diameters, keyways, and shear angles',
      'Consultation support for specialized composite boards',
    ],
    isFeatured: true,
    isAvailable: true,
  },

  // ===========================================================================
  // SUB-CATEGORY 3: PANEL PROCESSING MACHINES
  // ===========================================================================
  {
    name: 'Panel Saw',
    slug: 'panel-saw',
    brand: 'MODUPRO',
    categoryName: 'Panel processing machines',
    categorySlug: 'panel-processing-machines',
    shortDescription: 'Heavy-duty sliding table panel saw for precision sheet cutting and chip-free panel sizing.',
    fullDescription: 'MODUPRO supplies industrial sliding table panel saws with smooth sliding carriages, digital angle fences, and integrated scoring units for chip-free panel cutting in modular factories.',
    image: '/assets/products/Panel Processing Machine/0bf33efa-2086-46f2-a301-bac10a5b599c-Photoroom.png',
    mockupImage: '/assets/products/Panel Processing Machine/0bf33efa-2086-46f2-a301-bac10a5b599c-Photoroom.png',
    badge: 'PANEL SAW',
    applications: ['Modular furniture', 'Modular Kitchens', 'Doors Manufacturer', 'Wood Working industries'],
    features: [
      'Sliding carriage with hardened cylindrical steel guide ways',
      'Dual independent motors for main saw and scoring blade',
      'Crosscut fence with digital flip stops',
    ],
    isFeatured: true,
    isAvailable: true,
  },
  {
    name: 'Multi Boring Machine',
    slug: 'multi-boring-machine',
    brand: 'MODUPRO',
    categoryName: 'Panel processing machines',
    categorySlug: 'panel-processing-machines',
    shortDescription: 'Single and multi-head drilling machinery for rapid 32mm system modular furniture production.',
    fullDescription: 'Multi-boring machines engineered for horizontal and vertical dowel drilling, hinge cup boring, and shelf pin holes with fast pneumatic positioning.',
    image: '/assets/products/Panel Processing Machine/image-Photoroom (1).png',
    mockupImage: '/assets/products/Panel Processing Machine/image-Photoroom (1).png',
    badge: 'MULTI BORING',
    applications: ['Modular furniture', 'Modular Kitchens'],
    features: [
      'Pneumatic tilting boring heads (0° to 90°)',
      'Standard 32mm center-to-center spindle pitch',
      'Pneumatic workpiece clamps for high repeat accuracy',
    ],
    isFeatured: true,
    isAvailable: true,
  },
  {
    name: 'Cold Press Machine',
    slug: 'cold-press-machine',
    brand: 'MODUPRO',
    categoryName: 'Panel processing machines',
    categorySlug: 'panel-processing-machines',
    shortDescription: 'Hydraulic cold press machines for uniform lamination and flat panel pressing.',
    fullDescription: 'High-tonnage hydraulic cold presses delivering balanced pressure distribution across the entire bed for laminate bonding on ply, MDF, and blockboard.',
    image: '/assets/products/Panel Processing Machine/IMG_9659-Photoroom.png',
    mockupImage: '/assets/products/Panel Processing Machine/IMG_9659-Photoroom.png',
    badge: 'COLD PRESS',
    applications: ['Doors Manufacturer', 'Modular furniture', 'Wood Working industries'],
    features: [
      'Heavy welded steel framework for zero bed deflection',
      'Synchronized multi-cylinder hydraulic pressure circuit',
      'Adjustable pressing timer with automatic decompression',
    ],
    isFeatured: true,
    isAvailable: true,
  },
  {
    name: 'Automatic Edge Bander',
    slug: 'automatic-edge-bander',
    brand: 'MODUPRO',
    categoryName: 'Panel processing machines',
    categorySlug: 'panel-processing-machines',
    shortDescription: 'Automated continuous edge banding machine for PVC, ABS, and veneer tape application.',
    fullDescription: 'Comprehensive edge banding units featuring pre-milling, glue pot dosing, end trimming, fine top/bottom trimming, corner rounding, and scraping stations.',
    image: '/assets/products/Panel Processing Machine/4d1fe137-3b71-4fba-a9bf-b0a31a5aee17-Photoroom.png',
    mockupImage: '/assets/products/Panel Processing Machine/4d1fe137-3b71-4fba-a9bf-b0a31a5aee17-Photoroom.png',
    badge: 'AUTOMATIC EDGE BANDER',
    applications: ['Modular furniture', 'Modular Kitchens', 'Wood Working industries'],
    features: [
      'Quick-heat Teflon coated glue tank',
      'Pre-milling cutters for clean edge preparation',
      'High-frequency trimming and corner rounding units',
      'Radius scraping and buffing wheels for pristine finishes',
    ],
    isFeatured: true,
    isAvailable: true,
  },
  {
    name: 'CNC Router',
    slug: 'cnc-router',
    brand: 'MODUPRO',
    categoryName: 'Panel processing machines',
    categorySlug: 'panel-processing-machines',
    shortDescription: '3-axis and multi-axis CNC nesting and routing centers for automated sheet processing.',
    fullDescription: 'High-speed CNC routers with vacuum bed clamping, automatic tool changer (ATC), and precision linear guides for nesting, carving, and complex panel machining.',
    image: '/assets/products/Panel Processing Machine/586f2b47-642a-402c-9e3f-91986a5c0779-Photoroom.png',
    mockupImage: '/assets/products/Panel Processing Machine/586f2b47-642a-402c-9e3f-91986a5c0779-Photoroom.png',
    badge: 'CNC ROUTER',
    applications: ['Modular furniture', 'Modular Kitchens', 'Doors Manufacturer', 'Wood Working industries'],
    features: [
      'Multi-zone matrix vacuum hold-down bed',
      'High-power air/liquid cooled electro-spindle',
      'Compatible with leading CAD/CAM nesting software',
    ],
    isFeatured: true,
    isAvailable: true,
  },
  {
    name: 'Cold / Hot Press Machines',
    slug: 'cold-hot-press-machines',
    brand: 'MODUPRO',
    categoryName: 'Panel processing machines',
    categorySlug: 'panel-processing-machines',
    shortDescription: 'Thermal and ambient press machinery for plywood, door manufacturing, and veneer lamination.',
    fullDescription: 'Industrial heated platen and ambient hydraulic presses ensuring controlled temperature and pressure cycles for door cores and architectural panels.',
    image: '/assets/products/Panel Processing Machine/IMG_9659-Photoroom.png',
    mockupImage: '/assets/products/Panel Processing Machine/IMG_9659-Photoroom.png',
    badge: 'COLD/HOT PRESS',
    applications: ['Doors Manufacturer', 'Wood Working industries', 'Modular furniture'],
    features: [
      'Multi-daylight heated platens for thermal curing',
      'Independent platen temperature monitoring and regulation',
      'Heavy-duty hydraulic pistons for uniform surface contact',
    ],
    isFeatured: false,
    isAvailable: true,
  },

  // ===========================================================================
  // SUB-CATEGORY 4: PVC EDGE BANDING TAPES AND HARDWARE
  // ===========================================================================
  {
    name: 'PVC Edge Banding Tapes',
    slug: 'pvc-edge-banding-tapes',
    brand: 'MODUPRO',
    categoryName: 'PVC edge banding tapes and hardware',
    categorySlug: 'pvc-edge-banding-hardware',
    shortDescription: 'Trading of high-grade PVC edge banding tapes available in solid colors, wood grains, and textures.',
    fullDescription: 'MODUPRO trades high-grade PVC Edge Banding Tapes formulated with high-impact polymer for uniform flexibility, clean trimming, and solid primer backing that ensures seamless adhesion with Adhhesi Pro and Lockpro adhesives.',
    image: '/assets/products/pvg edge banding tapes/image-Photoroom.png',
    mockupImage: '/assets/products/pvg edge banding tapes/image-Photoroom.png',
    badge: 'PVC Edge Banding',
    applications: ['Modular furniture', 'Modular Kitchens', 'Doors Manufacturer'],
    features: [
      'Trading of PVC Edge Banding Tapes in diverse thicknesses and widths',
      'Pre-primed back side for maximum adhesive grab',
      'Clean trimming without edge whitening stress marks',
    ],
    isFeatured: true,
    isAvailable: true,
  },
  {
    name: 'Solid & Textured PVC Edge Tapes',
    slug: 'solid-textured-pvc-edge-tapes',
    brand: 'MODUPRO',
    categoryName: 'PVC edge banding tapes and hardware',
    categorySlug: 'pvc-edge-banding-hardware',
    shortDescription: 'Solid colors, super matte, high gloss, and natural woodgrain PVC edge banding rolls.',
    fullDescription: 'Premium rolls in diverse shades matching popular laminate decors in the Indian market. Moisture-resistant and high impact-absorbing formulation.',
    image: '/assets/products/pvg edge banding tapes/green.jpg.jpeg',
    mockupImage: '/assets/products/pvg edge banding tapes/green.jpg.jpeg',
    badge: 'PVC Tapes',
    applications: ['Modular furniture', 'Modular Kitchens'],
    features: [
      'Consistent thickness and roll winding',
      'High surface UV protection against fading',
      'Compatible with automatic edge banders',
    ],
    isFeatured: false,
    isAvailable: true,
  },
  {
    name: '2D Hinges',
    slug: '2d-hinges',
    brand: 'MODUPRO',
    categoryName: 'PVC edge banding tapes and hardware',
    categorySlug: 'pvc-edge-banding-hardware',
    shortDescription: 'Two-dimensional adjustable concealed hinges for modular cabinet doors.',
    fullDescription: 'Trading of 2D concealed hinges engineered for smooth movement, reliable door alignment, and durable cycle life across modular furniture units.',
    image: '/assets/products/pvg edge banding tapes/ChatGPT Image Aug 8, 2026, 01_11_17 PM-Photoroom.png',
    mockupImage: '/assets/products/pvg edge banding tapes/ChatGPT Image Aug 8, 2026, 01_11_17 PM-Photoroom.png',
    badge: '2D Hinges',
    applications: ['Modular furniture', 'Modular Kitchens'],
    features: [
      'Standard 35mm cup diameter',
      'Two-way screw adjustment for door alignment',
      'Sturdy nickel-plated steel body for corrosion resistance',
    ],
    isFeatured: false,
    isAvailable: true,
  },
  {
    name: '3D Hinges',
    slug: '3d-hinges',
    brand: 'MODUPRO',
    categoryName: 'PVC edge banding tapes and hardware',
    categorySlug: 'pvc-edge-banding-hardware',
    shortDescription: 'Three-way adjustable soft-closing hydraulic hinges for precision furniture door installations.',
    fullDescription: 'Trading of 3D adjustable hinges providing height, depth, and side adjustments with integrated hydraulic damping for silent closing in modular kitchens and wardrobes.',
    image: '/assets/products/pvg edge banding tapes/ChatGPT Image Aug 8, 2026, 01_11_17 PM-Photoroom.png',
    mockupImage: '/assets/products/pvg edge banding tapes/ChatGPT Image Aug 8, 2026, 01_11_17 PM-Photoroom.png',
    badge: '3D Hinges',
    applications: ['Modular furniture', 'Modular Kitchens'],
    features: [
      'Full 3-way adjustment (horizontal, vertical, depth)',
      'Integrated silent hydraulic soft-closing damper',
      'Clip-on mounting plate for tool-free door installation',
    ],
    isFeatured: true,
    isAvailable: true,
  },
  {
    name: 'Telescopic Channels',
    slug: 'telescopic-channels',
    brand: 'MODUPRO',
    categoryName: 'PVC edge banding tapes and hardware',
    categorySlug: 'pvc-edge-banding-hardware',
    shortDescription: 'Heavy-duty ball bearing telescopic drawer slides for smooth drawer extension.',
    fullDescription: 'Trading of precision telescopic drawer runner channels engineered for smooth gliding, high load ratings, and long-term durability in modular drawer units.',
    image: '/assets/products/pvg edge banding tapes/ChatGPT Image Aug 8, 2026, 01_11_04 PM-Photoroom.png',
    mockupImage: '/assets/products/pvg edge banding tapes/ChatGPT Image Aug 8, 2026, 01_11_04 PM-Photoroom.png',
    badge: 'Telescopic Channels',
    applications: ['Modular furniture', 'Modular Kitchens'],
    features: [
      'Full extension 3-fold ball bearing runner design',
      'Electro-galvanized / black finish for corrosion resistance',
      'Smooth, low-noise gliding with hardened steel ball bearings',
    ],
    isFeatured: true,
    isAvailable: true,
  },
  {
    name: '6 GMS CAM, Nylon Bush & Bolt',
    slug: '6-gms-cam-nylon-bush-bolt',
    brand: 'MODUPRO',
    categoryName: 'PVC edge banding tapes and hardware',
    categorySlug: 'pvc-edge-banding-hardware',
    shortDescription: '6 GMS CAM connectors, nylon expansion bushes, and connecting bolts for knock-down furniture assembly.',
    fullDescription: 'Trading of structural furniture hardware: 6 GMS CAM (minifix eccentric fittings), virgin nylon bushes, and precision-threaded connecting bolts for rigid 90-degree panel joints in modular furniture.',
    image: '/assets/products/pvg edge banding tapes/image-Photoroom (1).png',
    mockupImage: '/assets/products/pvg edge banding tapes/image-Photoroom (1).png',
    badge: '6 GMS CAM / Bush / Bolt',
    applications: ['Modular furniture', 'Modular Kitchens'],
    features: [
      '6 GMS high-density die-cast zinc CAM connectors',
      'Virgin nylon bushes preventing screw tear-out in composite boards',
      'Precision-threaded connecting bolts compatible with standard KD systems',
    ],
    isFeatured: true,
    isAvailable: true,
  },

  // ===========================================================================
  // SUB-CATEGORY 5: PANEL PROCESSING MACHINES, AND ITS SPARES (SHARES HARDWARE & MACHINE ASSETS)
  // ===========================================================================
  {
    name: 'Woodworking Machine Spares (All Makes)',
    slug: 'woodworking-machine-spares-all-make',
    brand: 'MODUPRO',
    categoryName: 'Panel processing machines, and its spares',
    categorySlug: 'machine-spares-services',
    shortDescription: 'Sales of spares of woodworking machines of all makes: feed rollers, glue pots, belts, cylinders, bearings.',
    fullDescription: 'MODUPRO is into sales of spares of woodworking machines of all makes. We stock feed rollers, glue tanks, timing belts, pneumatic cylinders, linear guide blocks, and cutter arbor components.',
    image: '/assets/products/pvg edge banding tapes/image-Photoroom (2).png',
    mockupImage: '/assets/products/pvg edge banding tapes/image-Photoroom (2).png',
    badge: 'Machine Spares',
    applications: ['Modular furniture', 'Wood Working industries'],
    features: [
      'Sales of spares of woodworking machines of all makes',
      'Tested for dimensional accuracy and load ratings',
      'Rapid dispatch from Nagpur depot to minimize machine downtime',
    ],
    isFeatured: true,
    isAvailable: true,
  },
  {
    name: 'Mechanical Spares & Components',
    slug: 'mechanical-spares-components-sub',
    brand: 'MODUPRO',
    categoryName: 'Panel processing machines, and its spares',
    categorySlug: 'machine-spares-services',
    shortDescription: 'Bearings, drive gears, guide rails, feed tracks, and clamping units.',
    fullDescription: 'Precision replacement mechanical components engineered to restore machine tolerances, alignment, and smooth operation under demanding factory shifts.',
    image: '/assets/products/Panel Processing Machine/4d1fe137-3b71-4fba-a9bf-b0a31a5aee17-Photoroom.png',
    mockupImage: '/assets/products/Panel Processing Machine/4d1fe137-3b71-4fba-a9bf-b0a31a5aee17-Photoroom.png',
    badge: 'Mechanical Spares',
    applications: ['Wood Working industries'],
    features: [
      'Linear guide blocks and carriage rails',
      'Precision spindle bearings and bushings',
      'Drive sprockets, timing belts, and chain links',
    ],
    isFeatured: false,
    isAvailable: true,
  },
  {
    name: 'Electrical & Heating Spares',
    slug: 'electrical-heating-spares',
    brand: 'MODUPRO',
    categoryName: 'Panel processing machines, and its spares',
    categorySlug: 'machine-spares-services',
    shortDescription: 'Heating elements, temperature sensors, contactors, relays, and motor starters.',
    fullDescription: 'Certified electrical parts for machinery control panels, heating chambers on edge banders, and motor drive systems.',
    image: '/assets/products/Panel Processing Machine/0bf33efa-2086-46f2-a301-bac10a5b599c-Photoroom.png',
    mockupImage: '/assets/products/Panel Processing Machine/0bf33efa-2086-46f2-a301-bac10a5b599c-Photoroom.png',
    badge: 'Electrical Spares',
    applications: ['Wood Working industries'],
    features: [
      'Glue pot heating elements and thermocouple probes',
      'Heavy-duty magnetic contactors and motor overloads',
      'Photoelectric sensors and micro-limit switches',
    ],
    isFeatured: false,
    isAvailable: true,
  },
  {
    name: 'Computerized & CNC Spares',
    slug: 'computerized-cnc-spares-sub',
    brand: 'MODUPRO',
    categoryName: 'Panel processing machines, and its spares',
    categorySlug: 'machine-spares-services',
    shortDescription: 'Encoders, servo drives, PLC controllers, and HMI display screen replacements.',
    fullDescription: 'Original specification computerized automation spares to troubleshoot and resolve motion control faults on CNC machines and automated lines.',
    image: '/assets/products/Panel Processing Machine/586f2b47-642a-402c-9e3f-91986a5c0779-Photoroom.png',
    mockupImage: '/assets/products/Panel Processing Machine/586f2b47-642a-402c-9e3f-91986a5c0779-Photoroom.png',
    badge: 'CNC & PLC Spares',
    applications: ['Wood Working industries'],
    features: [
      'High-resolution rotary encoders and linear optical scales',
      'AC servo drives and stepper motor units',
      'Industrial PLC modules and HMI touch panels',
    ],
    isFeatured: false,
    isAvailable: true,
  },
  {
    name: 'Machine Installation, Maintenance & Repair Service',
    slug: 'machine-service-engineer-support',
    brand: 'MODUPRO',
    categoryName: 'Panel processing machines, and its spares',
    categorySlug: 'machine-spares-services',
    shortDescription: 'Service engineers installing, maintaining, troubleshooting, and repairing mechanical, electrical and computerized components of woodworking equipment.',
    fullDescription: 'MODUPRO service engineers handle installation, maintenance, troubleshooting, and repair for mechanical, electrical, and computerized components of woodworking equipment across all makes.',
    image: '/assets/products/Panel Processing Machine/4d1fe137-3b71-4fba-a9bf-b0a31a5aee17-Photoroom.png',
    mockupImage: '/assets/products/Panel Processing Machine/4d1fe137-3b71-4fba-a9bf-b0a31a5aee17-Photoroom.png',
    badge: 'Field Engineering Service',
    applications: ['Modular furniture', 'Doors Manufacturer', 'Wood Working industries'],
    features: [
      'Service engineers handling installation, maintenance, troubleshooting & repair',
      'Covers mechanical, electrical, and computerized components',
      'Support across panel saws, edge banders, CNC routers, multi-boring, and presses',
    ],
    isFeatured: true,
    isAvailable: true,
  },
  {
    name: 'Hardware & Machine Assembly Fittings Set',
    slug: 'hardware-machine-assembly-fittings-set',
    brand: 'MODUPRO',
    categoryName: 'Panel processing machines, and its spares',
    categorySlug: 'machine-spares-services',
    shortDescription: '6 GMS CAM, nylon bushes, connecting bolts, telescopic channels, and 2D/3D hinges.',
    fullDescription: 'Complete package of knockdown assembly hardware and replacement fittings for modular furniture and machine setups.',
    image: '/assets/products/pvg edge banding tapes/image-Photoroom (1).png',
    mockupImage: '/assets/products/pvg edge banding tapes/image-Photoroom (1).png',
    badge: 'Hardware & Spares',
    applications: ['Modular furniture', 'Modular Kitchens'],
    features: [
      '6 GMS CAM and nylon bushes',
      'Connecting bolts and knockdown fasteners',
      '2D and 3D soft-close hinges and telescopic channels',
    ],
    isFeatured: true,
    isAvailable: true,
  },
];

export const servicesData = [
  {
    serviceNumber: '01',
    name: 'Machine Installation & Commissioning',
    slug: 'machine-installation-commissioning',
    shortDescription: 'Precision setup, alignment, and commissioning of woodworking machines.',
    fullDescription: 'Expert on-site installation for panel saws, edge banders, CNC routers, and multi-boring machines. We ensure electrical phase balance, dust extraction pairing, pneumatic pressure tuning, and dimensional alignment.',
    handledComponents: ['Mechanical', 'Electrical', 'Computerized'],
    scope: [
      'Bed leveling and anchor stabilization',
      'Electrical line, phase balancing & ground fault testing',
      'Pneumatic circuit calibration and regulator adjustments',
      'Trial cuts, joint testing, and operator handover',
    ],
    applicableMachinery: ['Sliding Table Panel Saws', 'Multi Boring Machines', 'Automatic Edge Banders', 'CNC Routers', 'Cold/Hot Press'],
  },
  {
    serviceNumber: '02',
    name: 'Machine Maintenance',
    slug: 'machine-maintenance',
    shortDescription: 'Preventative maintenance routines to avoid unexpected factory downtime.',
    fullDescription: 'Structured preventative servicing programs designed to inspect high-wear components, check drive belts, calibrate electronic encoders, and lubricate linear motion systems.',
    handledComponents: ['Mechanical', 'Electrical'],
    scope: [
      'Linear guide rail and ball screw inspection',
      'Lubrication and pneumatic pressure verification',
      'Glue tank cleanout and temperature calibration',
      'Spindle runout and bearing check',
    ],
    applicableMachinery: ['Panel Saw', 'Edge Banding Machines', 'CNC Routers', 'Cold Press'],
  },
  {
    serviceNumber: '03',
    name: 'Machine Troubleshooting',
    slug: 'machine-troubleshooting',
    shortDescription: 'Fast diagnostic and troubleshooting support for woodworking machinery operational faults.',
    fullDescription: 'Expert diagnostic assistance to identify and isolate issues causing cutting defects, edge banding adhesion failures, electrical trips, or machine positioning errors.',
    handledComponents: ['Mechanical', 'Electrical', 'Computerized'],
    scope: [
      'Operational error analysis',
      'Sensors, encoders, and limit switch verification',
      'Glue pot temperature and feed synchronization review',
      'Pneumatic and hydraulic pressure diagnostics',
    ],
    applicableMachinery: ['Automatic Edge Bander', 'CNC Router', 'Panel Saw', 'Multi Boring'],
  },
  {
    serviceNumber: '04',
    name: 'Mechanical Repair',
    slug: 'mechanical-repair',
    shortDescription: 'Repair and overhaul of mechanical machine components, drives, and assemblies.',
    fullDescription: 'Service support for mechanical components of woodworking machines including arbor shafts, gearboxes, feed rollers, bearing replacements, and carriage guide re-alignment.',
    handledComponents: ['Mechanical'],
    scope: [
      'Spindle and arbor bearing replacement',
      'Drive chain and belt tension adjustment',
      'Feed track and pressure roller reconditioning',
      'Bed leveling and sliding table realignments',
    ],
    applicableMachinery: ['Sliding Table Panel Saw', 'Edge Bander', 'Cold Press', 'Multi Boring'],
  },
  {
    serviceNumber: '05',
    name: 'Electrical Repair',
    slug: 'electrical-repair',
    shortDescription: 'Repair and service of electrical components, heating circuits, and motor controls.',
    fullDescription: 'Service and repair of electrical subsystems including contactors, relays, heating elements, thermostatic controllers, motor starters, and wiring harnesses.',
    handledComponents: ['Electrical'],
    scope: [
      'Control panel rewiring and component renewal',
      'Heating element and sensor replacements',
      'Motor diagnostics and overload protection setup',
      'Safety interlock and emergency stop testing',
    ],
    applicableMachinery: ['Edge Banding Machines', 'Panel Saw', 'Press Machinery', 'CNC Router'],
  },
  {
    serviceNumber: '06',
    name: 'Computerized System Service',
    slug: 'computerized-system-service',
    shortDescription: 'Service and troubleshooting of computerized and CNC machine components.',
    fullDescription: 'Troubleshooting and calibration of computerized machine controllers, CNC axis drivers, PLC units, encoder feedbacks, and digital operator interfaces.',
    handledComponents: ['Computerized'],
    scope: [
      'PLC and numerical controller diagnostics',
      'Servo driver and stepper motor configuration',
      'HMI screen and input terminal troubleshooting',
      'Origin calibration and software parameter backups',
    ],
    applicableMachinery: ['CNC Router', 'Automatic Edge Bander', 'Panel Processing Machines'],
  },
  {
    serviceNumber: '07',
    name: 'Machine Spares Supply',
    slug: 'machine-spares-supply',
    shortDescription: 'Supply of original and compatible spare parts for woodworking machines.',
    fullDescription: 'MODUPRO supplies verified spare parts for panel processing machines to minimize downtime and preserve machine longevity.',
    handledComponents: ['Mechanical', 'Electrical', 'Computerized'],
    scope: [
      'Direct part identification from machine specifications',
      'Supply of high-wear mechanical and electrical parts',
      'Guidance on correct part installation and calibration',
    ],
    applicableMachinery: ['Panel Saw', 'Multi Boring', 'Edge Bander', 'CNC Router', 'Presses'],
  },
  {
    serviceNumber: '08',
    name: 'Woodworking Machine Service',
    slug: 'woodworking-machine-service',
    shortDescription: 'Full-spectrum service support for woodworking machines and plant equipment.',
    fullDescription: 'Comprehensive workshop service packages covering mechanical, electrical, and computerized machinery requirements to keep your manufacturing facility producing at full potential.',
    handledComponents: ['Mechanical', 'Electrical', 'Computerized'],
    scope: [
      'Complete workshop machinery audit',
      'Preventive servicing schedule planning',
      'Emergency breakdown response',
      'Operator machine handling guidance',
    ],
    applicableMachinery: ['All woodworking and panel processing machinery'],
  },
];

export const industriesData = [
  {
    name: 'Modular Furniture',
    slug: 'modular-furniture',
    description: 'Comprehensive solutions for modular wardrobe, workstation, and cabinet manufacturing units.',
    solutionsOffered: [
      'PVAC white glue and D2/D3 adhesives for carcass and joinery bonding',
      'TCT and PCD panel saw blades for chip-free melamine and particle board sizing',
      'Multiboring bits and CNC tooling for precise 32mm system drilling',
      'PVC edge banding tapes, CAM fittings, and telescopic channels',
      'Machine maintenance and installation for edge banders and panel saws',
    ],
    commonApplications: [
      'Office modular workstations and storage',
      'Residential wardrobes, beds, and study tables',
      'Flat-pack and knock-down furniture assembly',
      'Post-formed and edge-banded panel elements',
    ],
    applicableProducts: [
      'Lockpro WR 3 (D3)',
      'Lockpro 808',
      'PVAC White Glue',
      'Automatic Edge Bander',
      'TCT Panel Saw Blades',
      'PVC Edge Banding Tapes',
      '3D Hinges',
    ],
  },
  {
    name: 'Modular Kitchens',
    slug: 'modular-kitchens',
    description: 'Moisture-resistant adhesive systems, precision tooling, and hardware for modern modular kitchens.',
    solutionsOffered: [
      'Certified D3 and PUR water-resistant adhesives for damp kitchen environments',
      'Acrylic and PVC adhesives for high-gloss shutter lamination',
      'CNC routing bits for decorative shutter profiles and handle grooves',
      '3D adjustable soft-close hinges and corrosion-resistant hardware',
      'Troubleshooting and servicing for continuous edge banding lines',
    ],
    commonApplications: [
      'Base and overhead kitchen cabinet carcasses',
      'Water-exposed sink and countertop base units',
      'Acrylic, laminate, and membrane finish kitchen shutters',
      'Drawer pull-out boxes and hardware fitting',
    ],
    applicableProducts: [
      'Lockpro VUS PUR Adhesives',
      'Lockpro WR 3 (D3)',
      'Certified D3 Adhesives',
      'Acrylic Adhesives',
      '3D Hinges',
      'CNC Bits',
      'Edge Banding Machines',
    ],
  },
  {
    name: 'Door Manufacturing',
    slug: 'door-manufacturing',
    description: 'Heavy-duty bonding adhesives, press machinery, and sizing blades for flush and laminated doors.',
    solutionsOffered: [
      'High-strength D3 and PVAC adhesives for door core and face lamination',
      'Cold press and heated press machinery for uniform platen bonding',
      'Heavy-duty panel saw blades for door sizing and rebating',
      'Customised cutter tooling for door lock recesses and hinge pockets',
      'Mechanical and electrical service support for press machinery',
    ],
    commonApplications: [
      'Flush door internal frame and skin pressing',
      'Laminated and decorative membrane door manufacturing',
      'Solid core wooden doors and engineered stiles',
      'Acoustic and commercial interior doors',
    ],
    applicableProducts: [
      'Lockpro WR 3 (D3)',
      'PVAC White Glue',
      'Cold Press Machine',
      'Cold/Hot Press Machines',
      'TCT Panel Saw Blades',
      'Customised Tools',
    ],
  },
  {
    name: 'Woodworking Industries',
    slug: 'woodworking-industries',
    description: 'End-to-end tooling, machinery, service, and adhesives for commercial panel processing and timber mills.',
    solutionsOffered: [
      'Full spectrum of industrial adhesives: PVAC, D2, D3, PUR, and contact formulations',
      'Standard and customised woodworking cutting tools and diamond PCD blades',
      'Panel processing machines, CNC routers, and multi-boring equipment',
      'Original mechanical, electrical, and computerized machine spares',
      'Certified technician support for machine installation, troubleshooting, and repairs',
    ],
    commonApplications: [
      'Plywood and board lamination mills',
      'Commercial architectural woodwork and joinery',
      'Solid timber sizing and profiling operations',
      'Industrial panel cutting and nesting plants',
    ],
    applicableProducts: [
      'Lockpro VUS PUR Adhesives',
      'Lockpro 808 PR',
      'LockPro 707',
      'Panel Saw',
      'CNC Router',
      'Woodworking Machine Spares',
      'Machine Maintenance Service',
    ],
  },
];

export const seedDatabase = async () => {
  try {
    const mongoUri = process.env.MONGODB_URI || 'mongodb://127.0.0.1:27017/modupro_db';
    if (mongoose.connection.readyState === 0) {
      await mongoose.connect(mongoUri);
    }

    console.log('[Seed]: Clearing existing collections...');
    await ProductCategory.deleteMany({});
    await Product.deleteMany({});
    await Service.deleteMany({});
    await Industry.deleteMany({});

    console.log('[Seed]: Inserting categories...');
    await ProductCategory.insertMany(categoriesData);

    console.log('[Seed]: Inserting products...');
    await Product.insertMany(productsData);

    console.log('[Seed]: Inserting services...');
    await Service.insertMany(servicesData);

    console.log('[Seed]: Inserting industries...');
    await Industry.insertMany(industriesData);

    console.log('[Seed]: Database successfully populated with 5 core categories & 28 verified products.');
    return true;
  } catch (err) {
    console.error('[Seed Error]:', err.message);
    return false;
  }
};

// If run directly from CLI
if (process.argv[1]?.endsWith('seedData.js')) {
  seedDatabase().then(() => {
    mongoose.disconnect();
    process.exit(0);
  });
}
